# Site
name: 'Blog'
description: 'Personal blog of Kevin Gibson'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'kmg030375@gmail.com'
mailchimp-list: 'https://github.us18.list-manage.com/subscribe/post?u=dab332ed05be1bdf39bc5bb67&amp;id=a7296a3641'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    kevin:
      name:           Kevin
      site:           https://kevinmgibson.github.io/blog
      avatar:         assets/images/avatar3.jpg
      bio:            "Kevin Gibson lives in Toronto with his wife, daughter and son. He has worked as a Program Director and Director of Software Delivery at Rangle.io, and as a Scrum Master at Bell Media and the CBC."
      email:          kmg030375@gmail.com
      twitter:        https://twitter.com/KG46794093

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kevin
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
